### ISSUE TITLE
Bug in widgets demo

### ISSUE THREAD

**Issue by ed2050** [andy31lewis/brywidgets#2]
### Critical Bug
I found a critical bug in your brywidgets demo page at http://mathsanswers.org.uk/oddments/brywidgets/demo.html.

The page claims to list the 100 greatest singles of all time.  Yet somehow there are  four Oasis songs in the list instead of the expected zero.

Michael Jackson, U2, Queen, Guns N Roses, Led Zeppelin - these luminary performers only managed one entry.  Elvis Presley only scored two.  This strict data set is obviously not compatible with the result above.

If Oasis had a single entry then it could be a simple off-by-one error in the code.  Two entries, an input mixup with the worst songs of all time.  Three entries, I would suspect data compromise by state-sponsored hackers sowing a misinformation campaign to undermine the rule of law.  But four?  That's beyond the level of cosmic ray bit errors if the sun suddenly went nova and incinerated all non-Oasis music on Earth.  In that case we'd all be living in a charred, unforgiving hellscape that's inhospitable to life.  And the nova would likely cause problems too.

### Steps to reproduce

1. Plug in headphones
2. Turn on Wonderwall
3. SEEK IMMEDIATE MEDICAL ATTENTION.  Do not waste precious time calling poison control.  Flush ears immediately with heavy doses of Nirvana and Eminem. 
4. Pray to the god of your choosing for forgiveness.

I spotted other data errors like Green Day, Robbie Williams, Celine Dion, etc.  You also appear to have corrupted data, such as including Sweet Child of Mine instead of the vastly superior You Could Be Mine (not to mention Welcome to the Jungle).  No sense correcting those until the program logic is validated.

Best of luck.

**Comment by andy31lewis** [comment]
LOL!!!
I've been trying to remember where I copied this list from - I thought it was NME but I can't find a list that exactly matches.
It wouldn't be my personal list but I didn't want to spend time compiling and typing out my own preferences. Mine would have alot more from the 60s and 70s but that's just me showing my age.
Just to relieve your concerns, I don't own a single track by Oasis.
Thanks for giving me a laugh anyway!

**Comment by ed2050** [comment]
Glad to know there's still some sanity left in the world. 🙂

**Comment by andy31lewis** [comment]
I think we can close this now...
